# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/confint_2group_diff.ipynb.

# %% auto 0
__all__ = ['create_jackknife_indexes']

# %% ../nbs/API/confint_2group_diff.ipynb 4
def create_jackknife_indexes(data):
    """
    Given an array-like, creates a jackknife bootstrap.

    For a given set of data Y, the jackknife bootstrap sample J[i]
    is defined as the data set Y with the ith data point deleted.

    Keywords
    --------
    data: array-like

    Returns
    -------
    Generator that yields all jackknife bootstrap samples.
    """
    from numpy import arange, delete

    index_range = arange(0, len(data))
    return (delete(index_range, i) for i in index_range)

